services:
  zookeeper:
    image: quay.io/debezium/zookeeper:3.1
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: quay.io/debezium/kafka:3.1
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  connect:
    image: quay.io/debezium/connect:3.1
    container_name: debezium
    depends_on:
      - kafka
    ports:
      - "8083:8083"
    volumes:
      - ./drivers/ojdbc8.jar:/kafka/libs/ojdbc8.jar
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: "1"
      CONFIG_STORAGE_TOPIC: connect-configs
      OFFSET_STORAGE_TOPIC: connect-offsets
      STATUS_STORAGE_TOPIC: connect-status
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_CONNECTOR_CLIENT_CONFIG_OVERRIDE_POLICY: "All"
      CONNECT_CONSUMER_METADATA_MAX_AGE_MS: "5000"
      TZ: UTC

  oracle:
    image: gvenzl/oracle-xe:21-faststart
    container_name: oracle
    environment:
      ORACLE_PASSWORD: password
      TZ: UTC
    ports:
      - "1521:1521"
    volumes:
      - ./oracle/init.sql:/container-entrypoint-initdb.d/init.sql

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: demo
    ports:
      - "5432:5432"

